# Generated by Django 4.0.5 on 2022-06-14 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('meter_num', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='meter number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_charge', models.PositiveSmallIntegerField(verbose_name='water_charge')),
                ('late_fine', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='late_fine')),
                ('maintainance_charge', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maintainance_charge')),
                ('new_meter_cost', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='new_meter_cost')),
                ('extra_fees', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='extra_fees')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='discount')),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='total')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='entered by')),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwp.watermeter', verbose_name='water meter')),
            ],
        ),
    ]
