# Generated by Django 4.0.5 on 2022-06-14 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_reading', models.PositiveSmallIntegerField()),
                ('previous_reading', models.PositiveSmallIntegerField()),
                ('minimum_charge', models.PositiveSmallIntegerField()),
                ('extra_consumption_charge', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('read_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwp.watermeter')),
            ],
        ),
    ]
