# Generated by Django 4.0.5 on 2022-06-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwp', '0002_meterreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='water_meter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dwp.meterreading', verbose_name='water meter'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='extra_consumption_charge',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
