# Generated by Django 4.0.5 on 2022-06-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwp', '0003_alter_bill_water_meter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='extra_fees',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='extra fees'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='late_fine',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='late fine'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='maintainance_charge',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maintainance charge'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='new_meter_cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='new meter cost'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='water_charge',
            field=models.PositiveSmallIntegerField(verbose_name='water charge'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='date',
            field=models.DateField(),
        ),
    ]
