# Generated by Django 4.0.5 on 2022-06-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwp', '0005_alter_meterreading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is_paid'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='date',
            field=models.DateField(),
        ),
    ]
