# Generated by Django 4.0.5 on 2022-06-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwp', '0006_meterreading_is_paid_alter_meterreading_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is_paid'),
        ),
    ]
