# Generated by Django 4.0.5 on 2022-06-17 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwp', '0010_alter_bill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterreading',
            options={'verbose_name': 'meter reading', 'verbose_name_plural': 'meter readings'},
        ),
        migrations.AlterModelOptions(
            name='watermeter',
            options={'verbose_name': 'water meter', 'verbose_name_plural': 'water meters'},
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('meter reader', 'meter reader'), ('tap maintainer', 'tap maintainer')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.AlterField(
            model_name='bill',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwp.employee', verbose_name='entered by'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='read_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwp.employee', verbose_name='read by'),
        ),
    ]
