# Generated by Django 4.0.5 on 2022-06-17 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwp', '0011_alter_meterreading_options_alter_watermeter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
        migrations.AddField(
            model_name='employee',
            name='type_of_employee',
            field=models.CharField(choices=[('meter reader', 'meter reader'), ('tap maintainer', 'tap maintainer')], default='meter reader', max_length=30, verbose_name='type_of_employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='salary'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
